### ISSUE TITLE
Error: Cannot tap chapmanb/cbl: invalid syntax in tap!

### ISSUE THREAD

**Issue by yzhzu** [tseemann/homebrew-bioinformatics-linux#7]
```
==> Tapping chapmanb/cbl
正克隆到 '/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl'...
remote: Counting objects: 50, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 50 (delta 3), reused 18 (delta 1), pack-reused 0
Unpacking objects: 100% (50/50), done.
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb:7:in `<class:BcbioRnaseq>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bwakit.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bwakit.rb:7:in `<class:Bwakit>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/cancerit-allelecount.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/cancerit-allelecount.rb:7:in `<class:CanceritAllelecount>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/caveman.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/caveman.rb:7:in `<class:Caveman>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/cramtools.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/cramtools.rb:7:in `<class:Cramtools>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/cufflinks-binary.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/cufflinks-binary.rb:11:in `<class:CufflinksBinary>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/express-binary.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/express-binary.rb:11:in `<class:ExpressBinary>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/flux-simulator.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/flux-simulator.rb:7:in `<class:FluxSimulator>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/gvcftools.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/gvcftools.rb:7:in `<class:Gvcftools>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/impute2.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/impute2.rb:11:in `<class:Impute2>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/isaac-aligner.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/isaac-aligner.rb:7:in `<class:IsaacAligner>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/isaac-variant-caller.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/isaac-variant-caller.rb:7:in `<class:IsaacVariantCaller>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/libmaus.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/libmaus.rb:7:in `<class:Libmaus>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/lofreq.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/lofreq.rb:11:in `<class:Lofreq>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/metal-gwas.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/metal-gwas.rb:7:in `<class:MetalGwas>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/oncofuse.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/oncofuse.rb:7:in `<class:Oncofuse>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/pindel.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/pindel.rb:7:in `<class:Pindel>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/qsignature.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/qsignature.rb:7:in `<class:Qsignature>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/qsnp.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/qsnp.rb:7:in `<class:Qsnp>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/rsem.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/rsem.rb:7:in `<class:Rsem>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/s3gof3r.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/s3gof3r.rb:11:in `<class:S3gof3r>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/scalpel.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/scalpel.rb:7:in `<class:Scalpel>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/seqbuster.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/seqbuster.rb:6:in `<class:Seqbuster>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/speedseq.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/speedseq.rb:7:in `<class:Speedseq>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/staden_io_lib.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/staden_io_lib.rb:7:in `<class:StadenIoLib>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/theta2.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/theta2.rb:7:in `<class:Theta2>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/vt.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/vt.rb:7:in `<class:Vt>'
Please report this to the chapmanb/cbl tap!
Error: Cannot tap chapmanb/cbl: invalid syntax in tap!
```

**Comment by tseemann** [comment]
That tap no longer works.
